export const routes = {
  Home: "/",
  Company: "/cong-ty/:companyId",
  Chat: "/chat",
  Job: "/job/:jobId/:companyId",
  FindJob: "/findjob",
  login: "/login",
  RegisterForUser: "/register-user",
  RegisterForCompany: "/register-employer",
  RecruiterHome: "/recruiter-home",
  RecruitManagement: "/recruite-manage",
  RecruitById: "/recruite-manage/:recruitId",
  ManageResume: "/manage-resume",
  ManageResumeId: "/manage-resume/:resumeId",
}
