export const sampleData = [
  {
    jobName: "Frontend Developer",
    companyName: "Tech Solutions",
    salary: "10_15",
    address: "Q1",
    experience: "2_years",
    job: "software_it",
  },
  {
    jobName: "Backend Developer",
    companyName: "Innovative Labs",
    salary: "20_25",
    address: "Q7",
    experience: "3_years",
    job: "information_technology",
  },
  {
    jobName: "Sales Executive",
    companyName: "Global Trade Co.",
    salary: "15_20",
    address: "Q3",
    experience: "no_experience",
    job: "business_sales",
  },
  {
    jobName: "Marketing Specialist",
    companyName: "Creative Minds",
    salary: "30_50",
    address: "GO_VAP",
    experience: "4_5_years",
    job: "marketing_communication_advertising",
  },
  {
    jobName: "Office Assistant",
    companyName: "Enterprise Services",
    salary: "under_10",
    address: "TPHCM",
    experience: "under_1",
    job: "administrative_office",
  },
  {
    jobName: "Customer Support",
    companyName: "Happy Customers",
    salary: "negotiable",
    address: "BINH_THANH",
    experience: "above_5",
    job: "customer_service",
  },
  {
    jobName: "IT Support",
    companyName: "Tech Savvy",
    salary: "10_15",
    address: "THU_DUC",
    experience: "no_experience",
    job: "information_technology",
  },
  {
    jobName: "Product Manager",
    companyName: "Future Solutions",
    salary: "above_50",
    address: "TAN_BINH",
    experience: "3_years",
    job: "business_sales",
  },
  {
    jobName: "Digital Marketer",
    companyName: "AdVance Marketing",
    salary: "25_30",
    address: "Q10",
    experience: "2_years",
    job: "marketing_communication_advertising",
  },
  {
    jobName: "Receptionist",
    companyName: "HealthCare Group",
    salary: "under_10",
    address: "Q2",
    experience: "no_experience",
    job: "administrative_office",
  },
  {
    jobName: "Graphic Designer",
    companyName: "ArtWorks Studio",
    salary: "10_15",
    address: "Q5",
    experience: "2_years",
    job: "marketing_communication_advertising",
  },
  {
    jobName: "Project Manager",
    companyName: "Global Builders",
    salary: "20_25",
    address: "Q12",
    experience: "4_5_years",
    job: "administrative_office",
  },
  {
    jobName: "Business Analyst",
    companyName: "Market Insights",
    salary: "30_50",
    address: "BINH_TAN",
    experience: "above_5",
    job: "business_sales",
  },
  {
    jobName: "Accountant",
    companyName: "Finance Experts",
    salary: "15_20",
    address: "Q4",
    experience: "3_years",
    job: "administrative_office",
  },
  {
    jobName: "Software Engineer",
    companyName: "CodeMasters",
    salary: "25_30",
    address: "Q6",
    experience: "4_5_years",
    job: "software_it",
  },
  {
    jobName: "HR Specialist",
    companyName: "People Connect",
    salary: "negotiable",
    address: "PHU_NHUAN",
    experience: "2_years",
    job: "customer_service",
  },
  {
    jobName: "Operations Manager",
    companyName: "Efficient Co.",
    salary: "above_50",
    address: "Q11",
    experience: "above_5",
    job: "administrative_office",
  },
  {
    jobName: "Data Analyst",
    companyName: "Data Driven",
    salary: "15_20",
    address: "Q9",
    experience: "2_years",
    job: "information_technology",
  },
  {
    jobName: "Content Creator",
    companyName: "Media Hub",
    salary: "10_15",
    address: "CU_CHI",
    experience: "no_experience",
    job: "marketing_communication_advertising",
  },
  {
    jobName: "Sales Representative",
    companyName: "Top Sales",
    salary: "20_25",
    address: "NHA_BE",
    experience: "under_1",
    job: "business_sales",
  },
  {
    jobName: "Network Engineer",
    companyName: "Web Net",
    salary: "30_50",
    address: "HOC_MON",
    experience: "4_5_years",
    job: "information_technology",
  },
  {
    jobName: "Financial Advisor",
    companyName: "Wealth Partners",
    salary: "above_50",
    address: "CAN_GIO",
    experience: "above_5",
    job: "business_sales",
  },
  {
    jobName: "Legal Advisor",
    companyName: "Law Hub",
    salary: "25_30",
    address: "Q8",
    experience: "4_5_years",
    job: "administrative_office",
  },
  {
    jobName: "UX/UI Designer",
    companyName: "User Focus",
    salary: "15_20",
    address: "BINH_CHANH",
    experience: "2_years",
    job: "software_it",
  },
  {
    jobName: "Executive Assistant",
    companyName: "Corporate Solutions",
    salary: "under_10",
    address: "Q10",
    experience: "no_experience",
    job: "administrative_office",
  },
  {
    jobName: "Product Designer",
    companyName: "Creative Solutions",
    salary: "20_25",
    address: "Q1",
    experience: "3_years",
    job: "marketing_communication_advertising",
  },
  {
    jobName: "Customer Service Rep",
    companyName: "Help Desk",
    salary: "under_10",
    address: "Q5",
    experience: "no_experience",
    job: "customer_service",
  },
  {
    jobName: "Junior Developer",
    companyName: "Tech Ventures",
    salary: "10_15",
    address: "Q6",
    experience: "under_1",
    job: "software_it",
  },
  {
    jobName: "Senior Developer",
    companyName: "Code Innovators",
    salary: "above_50",
    address: "Q3",
    experience: "above_5",
    job: "information_technology",
  },
  {
    jobName: "Social Media Manager",
    companyName: "Online Buzz",
    salary: "25_30",
    address: "GO_VAP",
    experience: "3_years",
    job: "marketing_communication_advertising",
  },
  {
    jobName: "Logistics Coordinator",
    companyName: "Ship Now",
    salary: "15_20",
    address: "Q11",
    experience: "2_years",
    job: "administrative_office",
  },
]
